### ISSUE TITLE
OpenBrush running on Pico

### ISSUE THREAD

**Issue by kris-w-dev** [icosa-mirror/com.unity.xr.openxr.picoxr#1]
hi, I would like to run OpenBrush on Pico. Can you give me some advice?  This repository doesn't seem complete yet.

**Comment by mikeskydev** [comment]
Hi, you can get Pico builds from our official repository: https://github.com/icosa-foundation/open-brush/releases. We publish to the Pico Global store as well, but not to China just yet.
